[versions]
junit-jupiter-engine = "5.11.1"
junit-platform = "junit-platform-launcher"

utility = "1.1.1"

# Plugins
shadow = "9.0.0-beta6"

[libraries]
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
junit-jetbrains = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

utility = { module = "com.github.esotericfoundation:utility.kt", version.ref = "utility" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.21" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
