[versions]
# Java
java = "21"

# Libraries
## Utility
utility = "1.1.1"

## Test
junit-jupiter-engine = "5.11.1"

kotlin-mock = "1.13.16"

# Plugins
plugin-kotlin-jvm = "2.0.21"

plugin-release-axion = "1.14.4"

plugin-shadow = "9.0.0-beta8"

plugin-dokka = "2.0.0"

[libraries]
# Utility
utility = { module = "com.github.esotericfoundation:utility.kt", version.ref = "utility" }

# Test
junit-platform = "org.junit.platform:junit-platform-launcher:junit-platform-launcher"
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }
junit-jetbrains = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }

kotlin-mock = { module = "io.mockk:mockk", version.ref = "kotlin-mock"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "plugin-kotlin-jvm" }

release-axion = { id = "pl.allegro.tech.build.axion-release", version.ref = "plugin-release-axion" }

shadow = { id = "com.gradleup.shadow", version.ref = "plugin-shadow" }

dokka = { id = "org.jetbrains.dokka", version.ref = "plugin-dokka" }
