name: Dokka Documentation

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  dokka:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: HTML
        run: gradle dokkaHtml
      - name: Jekyll
        run: gradle dokkaJekyll
      - name: Javadoc
        run: gradle dokkaJavadoc
      - name: GFM
        run: gradle dokkaGfm
