name: Dokka Documentation

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: write

jobs:
  dokka:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: HTML
        run: gradle dokkaHtml
      - name: Jekyll
        run: gradle dokkaJekyll
      - name: Javadoc
        run: gradle dokkaJavadoc
      - name: GFM
        run: gradle dokkaGfm
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          rm -rf *
          cp -r build/dokka/html/* .
          touch .nojekyll
          git add .
          git commit -m "[ci skip] Update Dokka documentation" || exit 0
          git push origin gh-pages --force
