name: dokka

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  dokka:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
      fail-fast: true
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Generate Dokka HTML files
        run: gradle dokkaHtml
      - name: Generate Dokka Jekyll files
        run: gradle dokkaJekyll
      - name: Generate Dokka Javadoc files
        run: gradle dokkaJavadoc
      - name: Generate Dokka GFM files
        run: gradle dokkaGfm
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git checkout --orphan gh-pages

          shopt -s dotglob extglob
          rm -rf !(build|.git)
          shopt -u dotglob extglob

          mv ./build/dokka/html/* ./
          rm -rf build

          git add ./
          git commit -m "GitHub Pages updates"

          git push --force -u origin gh-pages
