name: Dokka Documentation

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: write

jobs:
  dokka:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Generate Dokka HTML files
        run: gradle dokkaHtml
      - name: Generate Dokka Jekyll files
        run: gradle dokkaJekyll
      - name: Generate Dokka Javadoc files
        run: gradle dokkaJavadoc
      - name: Generate Dokka GFM files
        run: gradle dokkaGfm
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Check if gh-pages branch exists remotely
          if ! git ls-remote --exit-code --heads origin gh-pages; then
            git checkout --orphan gh-pages
            git rm -rf .
            touch README.md
            echo "# GitHub Pages" > README.md
            git add README.md
            git commit -m "Initial commit for GitHub Pages"
            git push origin gh-pages
          fi

          # Use a separate directory for the gh-pages worktree
          git worktree add gh-pages-dir gh-pages

          # Ensure it's clean
          rm -rf gh-pages-dir/*
          cp -r build/dokka/html/* gh-pages-dir/
          touch gh-pages-dir/.nojekyll  # Ensure GitHub Pages serves files correctly

          # Commit and push changes
          cd gh-pages-dir
          git add .
          git commit -m "[ci skip] Update Dokka documentation" || exit 0
          git push origin gh-pages
