name: dokka

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

permissions:
  contents: write

jobs:
  dokka:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 21 ]
      fail-fast: true
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Generate Dokka module HTML files
        run: gradle dokkaGenerateModuleHtml
      - name: Generate Dokka HTML files
        run: gradle dokkaGenerate
      - name: Setup Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Deploy to GitHub Pages
        run: |
          version=$(git describe --tags --abbrev=0)

          if ! git describe --exact-match --tags HEAD >/dev/null 2>&1; then
            version="${version}-SNAPSHOT"
          fi

          git checkout --orphan gh-pages

          shopt -s dotglob extglob
          rm -rf !(project|.git|.github)

          cd ./project

          rm -rf !(build)
          shopt -u dotglob extglob

          mkdir -p ./docs/$version

          mv ./project/build/dokka/html/* ./docs/$version
          rm -rf build

          git add ./
          git commit -m "GitHub Pages updates"

          git push --force -u origin gh-pages
