name: markdown

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@v1.218.0
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Install Markdown Lint Tool
        run: gem install mdl
      - name: Lint
        run: mdl .
