name: spellcheck
on: push

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Check spelling
      uses: rojopolis/spellcheck-github-actions@v0
      with:
        task_name: Markdown
        source_files: |
          '**/*.md'
